# Generated by Django 5.2 on 2025-05-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('temperatura_actual', models.FloatField()),
                ('temperatura_sensacion', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado_clima', models.CharField(max_length=50)),
                ('humedad', models.IntegerField()),
                ('velocidad_viento', models.FloatField()),
                ('direccion_viento', models.IntegerField()),
                ('probabilidad_lluvia', models.FloatField()),
            ],
            options={
                'db_table': 'clima',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('numeric_code', models.CharField(max_length=3)),
                ('phonecode', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('tld', models.CharField(max_length=10)),
                ('native', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('timezones', models.JSONField()),
                ('translations', models.JSONField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('emoji', models.CharField(max_length=10)),
                ('emojiU', models.CharField(max_length=20)),
                ('flag', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lugar',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_lugar',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_transporte',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.countries')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('dia', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.cities')),
                ('clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.clima')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.countries')),
            ],
            options={
                'db_table': 'itinerario',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('orden', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.itinerario')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Actividad_Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.actividad')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.lugar')),
            ],
            options={
                'db_table': 'actividad_lugar',
                'unique_together': {('actividad', 'lugar')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugares',
            field=models.ManyToManyField(through='chatbot.Actividad_Lugar', to='chatbot.lugar'),
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.countries')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.states'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.tipo_lugar'),
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.tipo_transporte')),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.AddField(
            model_name='itinerario',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.transporte'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_salida', models.DateField()),
                ('duracion_viaje', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('ciudad_salida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.cities')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
        migrations.AddField(
            model_name='itinerario',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.viaje'),
        ),
    ]
