# Generated by Django 5.2 on 2025-04-21 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(max_length=255)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='chatbot.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('restaurante', 'Restaurante'), ('hotel', 'Hotel'), ('club', 'Club'), ('centro_turistico', 'Centro Turístico')], max_length=50)),
                ('nombre_destino', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='chatbot.viaje')),
            ],
        ),
    ]
