# Generated by Django 5.2 on 2025-05-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clima',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='clima',
            name='direccion_viento',
        ),
        migrations.RemoveField(
            model_name='clima',
            name='temperatura_actual',
        ),
        migrations.RemoveField(
            model_name='clima',
            name='temperatura_sensacion',
        ),
        migrations.RemoveField(
            model_name='clima',
            name='velocidad_viento',
        ),
        migrations.AddField(
            model_name='clima',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.cities'),
        ),
        migrations.AddField(
            model_name='clima',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clima',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.countries'),
        ),
        migrations.AddField(
            model_name='clima',
            name='temperatura_maxima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clima',
            name='temperatura_minima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clima',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
