# Generated by Django 5.2 on 2025-05-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_clima_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clima',
            unique_together={('fecha', 'ciudad', 'pais')},
        ),
    ]
