# Generated by Django 5.2 on 2025-06-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_clima_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarGooglePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=500)),
                ('tipo_principal', models.CharField(max_length=100)),
                ('tipos_adicionales', models.JSONField(default=list)),
                ('categoria', models.CharField(choices=[('restaurantes', 'Restaurantes'), ('hoteles', 'Hoteles'), ('lugares_acuaticos', 'Lugares Acuáticos'), ('lugares_turisticos', 'Lugares Turísticos'), ('discotecas', 'Discotecas'), ('museos', 'Museos'), ('lugares_campestres', 'Lugares Campestres'), ('centros_comerciales', 'Centros Comerciales'), ('lugares_de_entretenimiento', 'Lugares de Entretenimiento')], max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('rating', models.FloatField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_precios', models.IntegerField(default=0)),
                ('horarios', models.JSONField(default=list)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_negocio', models.CharField(default='OPERATIONAL', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lugar_google_places',
                'indexes': [models.Index(fields=['categoria'], name='lugar_googl_categor_512b54_idx'), models.Index(fields=['latitud', 'longitud'], name='lugar_googl_latitud_f97585_idx'), models.Index(fields=['rating'], name='lugar_googl_rating_bb5765_idx')],
                'unique_together': {('nombre', 'direccion', 'latitud', 'longitud')},
            },
        ),
    ]
