# Generated by Django 5.2 on 2025-06-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_lugargoogleplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('rango_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rango_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nivel_precio',
                'ordering': ['nivel'],
            },
        ),
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='nivel_precios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.nivelprecio'),
        ),
    ]
