# Generated by Django 5.2 on 2025-06-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_nivelprecio_alter_lugargoogleplaces_nivel_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugargoogleplaces',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
