# Generated by Django 5.2 on 2025-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_lugargoogleplaces_resumen_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='resumen_ia',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
