# Generated by Django 5.2 on 2025-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_lugargoogleplaces_resumen_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugargoogleplaces',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
