# Generated by Django 5.2 on 2025-06-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_lugargoogleplaces_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
