# Generated by Django 5.2 on 2025-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_lugargoogleplaces_resumen_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugargoogleplaces',
            name='caracteristicas_extraidas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
