# Generated by Django 5.2 on 2025-06-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_add_caracteristicas_extraidas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lugargoogleplaces',
            name='lugar_googl_categor_512b54_idx',
        ),
        migrations.RemoveField(
            model_name='lugargoogleplaces',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='horarios',
            field=models.JSONField(default=list, help_text='Horarios de operación por día'),
        ),
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='tipo_principal',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurante'), ('coffee_shop', 'Cafetería'), ('chinese_restaurant', 'Restaurante Chino'), ('bar', 'Bar'), ('lodging', 'Alojamiento'), ('aquarium', 'Acuario'), ('beach', 'Playa'), ('market', 'Mercado'), ('park', 'Parque'), ('museum', 'Museo'), ('church', 'Iglesia'), ('historical_landmark', 'Monumento Histórico'), ('tourist_attraction', 'Atracción Turística'), ('night_club', 'Club Nocturno'), ('bar_and_grill', 'Bar y Parrilla'), ('home_goods_store', 'Tienda de Hogar'), ('art_gallery', 'Galería de Arte'), ('shopping_mall', 'Centro Comercial'), ('store', 'Tienda'), ('supermarket', 'Supermercado'), ('food_store', 'Tienda de Comida'), ('discount_store', 'Tienda de Descuentos'), ('department_store', 'Tienda por Departamentos'), ('water_park', 'Parque Acuático'), ('movie_theater', 'Cine'), ('casino', 'Casino'), ('amusement_park', 'Parque de Diversiones'), ('amusement_center', 'Centro de Entretenimiento'), ('event_venue', 'Lugar de Eventos'), ('food', 'Comida'), ('point_of_interest', 'Punto de Interés'), ('establishment', 'Establecimiento'), ('bakery', 'Panadería'), ('cafe', 'Café'), ('dessert_shop', 'Tienda de Postres'), ('confectionery', 'Confitería'), ('ice_cream_shop', 'Heladería'), ('hamburger_restaurant', 'Restaurante de Hamburguesas'), ('american_restaurant', 'Restaurante Americano'), ('inn', 'Posada'), ('natural_feature', 'Característica Natural'), ('place_of_worship', 'Lugar de Culto'), ('historical_place', 'Lugar Histórico'), ('cafeteria', 'Cafetería'), ('brunch_restaurant', 'Restaurante de Brunch'), ('painter', 'Pintor'), ('courier_service', 'Servicio de Mensajería'), ('grocery_store', 'Tienda de Abarrotes'), ('wholesaler', 'Mayorista'), ('clothing_store', 'Tienda de Ropa'), ('sporting_goods_store', 'Tienda Deportiva'), ('furniture_store', 'Tienda de Muebles'), ('home_improvement_store', 'Tienda de Mejoras para el Hogar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugargoogleplaces',
            name='tipos_adicionales',
            field=models.JSONField(default=list, help_text='Lista de tipos adicionales del establecimiento'),
        ),
        migrations.AddIndex(
            model_name='lugargoogleplaces',
            index=models.Index(fields=['tipo_principal'], name='lugar_googl_tipo_pr_055e16_idx'),
        ),
        migrations.AddIndex(
            model_name='lugargoogleplaces',
            index=models.Index(fields=['place_id'], name='lugar_googl_place_i_b57365_idx'),
        ),
    ]
