# Generated by Django 5.2 on 2025-06-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_remove_lugargoogleplaces_lugar_googl_categor_512b54_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugargoogleplaces',
            name='caracteristicas_extraidas',
        ),
    ]
