# Generated by Django 5.2 on 2025-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_lugargoogleplaces_caracteristicas_extraidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugargoogleplaces',
            name='palabras_clave_ia',
            field=models.TextField(blank=True, help_text='Palabras clave extraídas del resumen para embeddings eficientes', null=True),
        ),
    ]
